### ISSUE TITLE
Why newtype-ts and monocle-ts are listed as peerDependencies and not dependencies ?

### ISSUE THREAD

**Issue by JalilArfaoui** [samhh/fp-ts-std#151]
I usually consider that any library that I do not import directly in my project code but is mandatory for the lib package to work should be a `dependency` …

With current configuration, installing only `fp-ts-std` in a project results in `Can't resolve 'newtype-ts' in '/working_dir/node_modules/fp-ts-std/dist/cjs'` at build time.

npm 1, 2 and 7 do not have this problem as missing peer dependencies are automatically installed (https://nodejs.org/es/blog/npm/peer-dependencies/)

**Comment by samhh** [comment]
The immediate answer is that it's because that's what the other libraries in the fp-ts ecosystem do, for example [io-ts](https://github.com/gcanti/io-ts/blob/e619fb1a769afb0dde3b17f4fc3ae28caa004466/package.json#L40).

The more thoughtful answer is that otherwise consumers for the frontend would end up bundling multiple versions of fp-ts et al. It may also prevent interop issues between different versions of these dependencies.

Your dependency management tool should warn you if you're missing peer dependencies. It's also mentioned near the top of the README.
