### ISSUE TITLE
Stricter `DOM` module

### ISSUE THREAD

**Issue by stefanoCrmg** [samhh/fp-ts-std#169]
Hello,

I was playing around with the `DOM` module and noticed a few things:

1. there's no `removeEventListener`
2. `addEventListener` is a bit loose in its typing.

What I mean is that the `type` parameter is just a `string` and a user can only add an event listener on a `n: Node` but I'd say that `Window` is a fairly common target for an event listener ...but `Window` does not extend `Node`!

So how about the following change?
```diff
-export const addEventListener = (type: string) => (f: (evt: Event) => IO<void>) => (x: Node): IO<void>
+const addEventListener: (type: keyof WindowEventMap) => (f: (evt: Event) => IO.IO<void>) => (x: Node | Window) => IO.IO<void>
```

And out of curiosity, would it makes sense to move all the functions in the module from being just `IO<A>` to something like`RIO<DOMEnv, A>`?
Where `DOMEnv` would be something like `type DOMEnv = { window: Window }`.
Of course this would result in stricter requirements on the user of the library, but wouldn't it make sense in the context of a bunch of APIs related to the DOM? 🤔 

I already have a PR ready for adding `removeEventListener` and a stricter `addEventListener` if needed, I just figured I'd ask before opening it.

**Comment by samhh** [comment]
I'd certainly be open to improvements to that module, it hasn't been fleshed out much.

You can probably target `document.body` or similar instead of `window`. But you're right, `window` is a very common target in the real world. One way or another that should be supported.

I'm sensing there are two fairly distinct ways of interacting with the DOM, one being via window and one being via specific nodes. Ideally we'd avoid the need of a DOM environment in the latter case, though maybe the tradeoff is worth it anyway.

If there's going to be an unchanging common dependency a `ReaderIO` makes a ton of sense. Even with a changing one that could work, but I'm not sure how you could model traversing the DOM in a fallible/Kleisli-ish way, thinking of the node use case.

Lots of questions I don't have answers to. 😄

**Comment by samhh** [comment]
I'll close this but feel free to make any further contributions. :slightly_smiling_face:
